using System;
using System.Collections.Generic;
using System.IO;

namespace TwoLayerSolution
{
    public class PersonGenerator
    {
        public PersonGenerator() {}

        private readonly string[] _names =
        {
            "Феликс",
            "Эдуард",
            "Шерлок",
            "Иннокентий",
            "Лука",
            "Гавриил",
            "Назар",
            "Леонард",
            "Оскар",
            "Цефас",
            "Ленар",
            "Филипп",
            "Цефас",
            "Ленар",
            "Эдуард",
            "Филипп",
            "Алексей",
            "Зуфар",
            "Прохор",
            "Ждан",
            "Глеб",
            "Чеслав",
            "Тимур",
            "Леонид",
            "Михаил",
            "Филипп",
            "Ждан",
            "Жигер",
            "Эрик",
            "Вениамин",
            "Денис",
            "Яромир",
            "Трофим",
            "Дан",
            "Устин",
            "Иннокентий",
            "Болеслав",
            "Геннадий",
            "Юлий",
            "Август",
            "Милан",
            "Ефрем",
            "Роман",
            "Святослав",
            "Жерар",
            "Феликс",
            "Филипп",
            "Стефан",
            "Вадим",
            "Сергей",
            "Спартак",
            "Игнатий",
            "Иосиф",
            "Динар",
            "Остап",
            "Устин",
            "Герасим",
            "Матвей",
            "Харитон",
            "Пётр",
            "Корнелий",
            "Максим",
            "Игнат",
            "Шарль",
            "Святослав",
            "Харитон",
            "Денис",
            "Святослав",
            "Йоган",
            "Роман",
            "Станислав",
            "Юлиан",
            "Марк",
            "Болеслав",
            "Станислав",
            "Георгий",
            "Прохор",
            "Валентин",
            "Цицерон",
            "Руслан",
            "Денис",
            "Сава",
            "Лукьян",
            "Тимофей",
            "Юлиан",
            "Болеслав",
            "Цицерон",
            "Чеслав",
            "Харитон",
            "Родион",
            "Трофим",
            "Ленар",
            "Харитон",
            "Харитон",
            "Николай",
            "Родион",
            "Евстахий",
            "Феликс",
            "Никита"
        };

        private readonly string[] _surnames =
        {
            "Галкин",
            "Дмитриев",
            "Дроздов",
            "Беляков",
            "Карпов",
            "Гаврилов",
            "Самойлов",
            "Третьяков",
            "Соловьёв",
            "Притула",
            "Блинов",
            "Савельев",
            "Костин",
            "Пилипейко",
            "Пасичник",
            "Козлов",
            "Тихонов",
            "Моисеенко",
            "Соколов",
            "Романов",
            "Зайцев",
            "Беляев",
            "Нестеров",
            "Коцюбинский",
            "Тимошенко",
            "Таранец",
            "Брагин",
            "Субботин",
            "Киселёв",
            "Яворивский",
            "Фокин",
            "Силин",
            "Уваров",
            "Абрамов",
            "Волков",
            "Ерёменко",
            "Кошелев",
            "Савельев",
            "Горбачёв",
            "Карпенко-Карый",
            "Хижняк",
            "Денисов",
            "Кузнецов",
            "Борисов",
            "Колобов",
            "Яковенко",
            "Забужко",
            "Лановой",
            "Коровяк",
            "Игнатов",
            "Красинец",
            "Лихачёв",
            "Макаров",
            "Лаврентьев",
            "Толочко",
            "Моисеев",
            "Легойда",
            "Панфилов",
            "Потапов",
            "Смирнов",
            "Виноградов",
            "Горшков",
            "Жуков",
            "Андреев",
            "Королёв",
            "Андреев",
            "Лапин",
            "Гребневский",
            "Саксаганский",
            "Зиновьев",
            "Мухин",
            "Повалий",
            "Горбунов",
            "Игнатов",
            "Трясило",
            "Белов",
            "Попов",
            "Кулибаба",
            "Котовский",
            "Новиков",
            "Новиков",
            "Трублаевский",
            "Сысоев",
            "Панфилов",
            "Гришин",
            "Мирный",
            "Буров",
            "Симоненко",
            "Рымар",
            "Меркушев",
            "Кириленко",
            "Горшков",
            "Горобчук",
            "Петров",
            "Сысоев",
            "Семёнов",
            "Максимов",
            "Лаврентьев",
            "Котов"
        };

        private readonly string[] _patronymic =
        {
            "Богданович",
            "Романович",
            "Валериевич",
            "Евгеньевич",
            "Анатолиевич",
            "Борисович",
            "Сергеевич",
            "Леонидович",
            "Дмитриевич",
            "Брониславович",
            "Васильевич",
            "Сергеевич",
            "Артёмович",
            "Артёмович",
            "Львович",
            "Юхимович",
            "Андреевич",
            "Евгеньевич",
            "Анатолиевич",
            "Борисович",
            "Викторович",
            "Борисович",
            "Эдуардович",
            "Евгеньевич",
            "Михайлович",
            "Максимович",
            "Сергеевич",
            "Ярославович",
            "Данилович",
            "Васильевич",
            "Сергеевич",
            "Сергеевич",
            "Платонович",
            "Васильевич",
            "Платонович",
            "Артёмович",
            "Ярославович",
            "Данилович",
            "Львович",
            "Иванович",
            "Богданович",
            "Вадимович",
            "Владимирович",
            "Викторович",
            "Максимович",
            "Артёмович",
            "Валериевич",
            "Эдуардович",
            "Юхимович",
            "Сергеевич",
            "Львович",
            "Петрович",
            "Фёдорович",
            "Брониславович",
            "Романович",
            "Александрович",
            "Борисович",
            "Андреевич",
            "Владимирович",
            "Платонович",
            "Алексеевич",
            "Петрович",
            "Михайлович",
            "Васильевич",
            "Петрович",
            "Михайлович",
            "Романович",
            "Леонидович",
            "Петрович",
            "Виталиевич",
            "Михайлович",
            "Борисович",
            "Романович",
            "Анатолиевич",
            "Артёмович",
            "Александрович",
            "Брониславович",
            "Алексеевич",
            "Иванович",
            "Виталиевич",
            "Владимирович",
            "Петрович",
            "Валериевич",
            "Юхимович",
            "Брониславович",
            "Романович",
            "Юхимович",
            "Михайлович",
            "Дмитриевич",
            "Александрович",
            "Брониславович",
            "Григорьевич",
            "Ярославович",
            "Леонидович",
            "Платонович",
            "Михайлович",
            "Алексеевич",
            "Петрович",
            "Сергеевич"
        };

        private readonly string[] _towns =
        {
            "Брагин",
            "Браслав",
            "Брест",
            "Витебск",
            "Воложин",
            "Гомель",
            "Гродно",
            "Жлобин",
            "Копыль",
            "Минск",
            "Могилёв",
            "Мозырь",
            "Мстиславль",
            "Мядель",
            "Орша",
            "Осиповичи",
            "Пинск",
            "Полоцк",
            "Свислочь",
            "Слоним",
            "Сметаничи",
            "Актюбинск",
            "Алма-Ата",
            "Аркалык",
            "Астана",
            "Атбасар",
            "Байконур",
            "Балхаш",
            "Гурьев",
            "Джамбул",
            "Джезказган",
            "Джетыгара",
            "Зыряновск",
            "Карабалык",
            "Караганда",
            "Кзыл-Орда",
            "Кокчетав",
            "Кустанай",
            "Лисаковск",
            "Павлодар",
            "Петропавловск",
            "Риддер",
            "Рудный",
            "Сарыагач",
            "Семипалатинск",
            "Степногорск",
            "Озёрск",
            "Октябрьский",
            "Омск",
            "Омутнинск",
            "Орёл",
            "Оренбург",
            "Орехово-Зуево",
            "Орск",
            "Островной",
            "Отрадная",
            "Очёр",
            "Павловский Посад",
            "Пангоды",
            "Пенза",
            "Первоуральск",
            "Переславль-Залесский",
            "Пермь",
            "Петрозаводск",
            "Петропавловск-Камчатский",
            "Подольск",
            "Покачи",
            "Приозерск",
            "Прокопьевск",
            "Псков",
            "Пятигорск",
            "Радужный",
            "Раменское",
            "Ржев",
            "Родники",
            "Россошь",
            "Ростов-на-Дону",
            "Рубцовск",
            "Рыбинск",
            "Рязань",
            "Салават",
            "Салехард",
            "Сальск",
            "Самара",
            "Санкт-Петербург",
            "Саранск",
            "Сарапул",
            "Саратов",
            "Саров",
            "Сатка",
            "Саяногорск",
            "Славгород",
            "Смоленск",
            "Снежинск",
            "Советск",
            "Советская Гавань",
            "Соликамск",
            "Сочи",
            "Ставрополь",
            "Старый Оскол",
            "Стерлитамак",
            "Стрежевой",
            "Ступино",
            "Суворов",
            "Сургут",
            "Сухиничи",
            "Сызрань",
            "Сыктывкар",
            "Таганрог",
            "Талдом",
            "Тамбов",
            "Тбилисская",
            "Тверь",
            "Темрюк",
            "Тихвин",
            "Тихорецк",
            "Тобольск",
            "Тольятти",
            "Томск",
            "Тотьма",
            "Трёхгорный",
            "Туапсе",
            "Тула",
            "Тулун",
            "Туринск",
            "Тында",
            "Тюмень",
            "Углич",
            "Удачный",
            "Ужур",
            "Улан-Удэ",
            "Ульяновск",
            "Уни",
            "Урай",
            "Усинск",
            "Усолье-Сибирское",
            "Уссурийск",
            "Усть-Илимск",
            "Усть-Мая",
            "Уфа",
            "Ухта",
            "Хабаровск",
            "Ханты-Мансийск",
            "Холмск",
            "Чайковский",
            "Чапаевск",
            "Чебоксары",
            "Челябинск",
            "Череповец",
            "Черкесск",
            "Черногорск",
            "Чернушка",
            "Черняховск",
            "Чистополь",
            "Чита",
            "Чусовой",
            "Шадринск",
            "Шарья",
            "Шарыпово",
            "Шатура",
            "Шахты",
            "Шемордан",
            "Лазоревское",
            "Лангепас",
            "Лесосибирск",
            "Ливны",
            "Ликино-Дулёво",
            "Липецк",
            "Лиски",
            "Луга",
            "Лысьва",
            "Людиново",
            "Лянтор",
            "Магадан",
            "Магнитогорск",
            "Майкоп",
            "Максатиха",
            "Малая Вишера",
            "Махачкала",
            "Мегион",
            "Междуреченск",
            "Миасс",
            "Минусинск",
            "Мирный",
            "Михайловка",
            "Мичуринск",
            "Можайск",
            "Можга",
            "Мончегорск",
            "Моршанск",
            "Москва",
            "Мосолово",
            "Муравленко",
            "Мурманск",
            "Муром",
            "Мценск",
            "Набережные Челны",
            "Надым",
            "Назарово",
            "Назрань",
            "Нальчик"
        };

        private readonly string[] _datesOfBirth =
        {
            "1975-10-17",
            "1977-02-02",
            "1977-10-25",
            "1979-06-21",
            "1980-03-01",
            "1980-05-01",
            "1981-01-30",
            "1981-02-03",
            "1982-12-22",
            "1985-06-08",
            "1989-01-02",
            "1989-08-25",
            "1991-02-08",
            "1991-10-09",
            "1992-01-20",
            "1994-03-18",
            "1995-03-03",
            "1995-08-08",
            "1996-05-30",
            "1996-11-13",
            "1997-09-17",
            "1997-12-30",
            "1998-03-26",
            "1998-08-31",
            "1998-09-21",
            "1975-11-12",
            "1976-09-11",
            "1976-12-03",
            "1978-05-18",
            "1979-10-22",
            "1981-01-08",
            "1981-06-04",
            "1982-04-05",
            "1983-06-04",
            "1983-06-13",
            "1984-08-14",
            "1985-12-20",
            "1986-12-24",
            "1987-07-23",
            "1987-12-11",
            "1988-12-30",
            "1989-10-04",
            "1990-11-10",
            "1991-07-20",
            "1993-05-05",
            "1995-05-13",
            "1995-06-06",
            "1995-06-17",
            "1996-01-24",
            "1996-07-10",
            "1975-01-10",
            "1978-05-26",
            "1980-01-12",
            "1980-06-14",
            "1980-11-11",
            "1982-04-24",
            "1982-07-24",
            "1983-05-11",
            "1983-05-28",
            "1984-02-21",
            "1984-10-29",
            "1985-12-21",
            "1986-07-29",
            "1986-12-19",
            "1987-10-03",
            "1988-08-26",
            "1988-09-26",
            "1989-08-31",
            "1989-12-08",
            "1990-03-13",
            "1991-12-19",
            "1992-03-07",
            "1993-06-01",
            "1997-06-04",
            "1997-11-12"
        };

        private readonly string[] _passportNumbers =
        {
            "2402014",
            "4702003",
            "1401067",
            "9508060",
            "5907067",
            "2605030",
            "4305015",
            "4203049",
            "4408066",
            "3307009",
            "7008041",
            "4309066",
            "9105045",
            "2010011",
            "9311044",
            "1204011",
            "1506060",
            "6310002",
            "5606049",
            "0600056",
            "3607053",
            "2811056",
            "4604015",
            "5900029",
            "0909067",
            "5902028",
            "4401058",
            "8505054",
            "9005020",
            "0703035",
            "8504047",
            "6402031",
            "6801038",
            "3404067",
            "2105065"
        };

        private readonly string[] _companies =
        {
            "Adapt",
            "Adaptabiz",
            "Adaptas",
            "Adaptaz",
            "Advansed Teksyztems",
            "Affinity Investment Group",
            "Afforda",
            "Afforda Merchant Services",
            "Alert Alarm Company",
            "Alladin Realty",
            "Alladin's Lamp",
            "Architectural Genie",
            "Asian Answers",
            "Asian Fusion",
            "Asian Junction",
            "Asian Plan",
            "Asian Solutions",
            "Asiatic Solutions",
            "Atlas Architectural Designs",
            "Atlas Realty",
            "Avant Garde Appraisal",
            "Avant Garde Appraisal Group",
            "Avant Garde Interior Designs",
            "Awthentikz",
            "Back To Basics Chiropractic Clinic",
            "Balanced Fortune",
            "Beasts of Beauty",
            "Belle Ladi",
            "Belle Lady",
            "Benesome",
            "Best Biz Survis",
            "Better Business Ideas and Services",
            "Buena Vista Garden Maintenance",
            "Buena Vista Realty Service",
            "Body Fate",
            "Body Toning",
            "Bold Ideas",
            "Bonanza Produce Stores",
            "Bountiful Harvest Health Food Store",
            "Brilliant Home Designs",
            "Capitalcorp",
            "Castle Realty",
            "Chargepal",
            "Choices",
            "Circuit Design",
            "Complete Tech",
            "Corinthian Designs",
            "Corpbay",
            "Cougar Investment",
            "Crazy Tiger",
            "Creative Wealth",
            "Creative Wealth Management",
            "Custom Lawn Care",
            "Custom Lawn Service",
            "Cut Above",
            "Cut Rite",
            "Cut Rite Lawn Care",
            "Datacorp",
            "Desert Garden Help",
            "Destiny Planners",
            "Destiny Realty",
            "Destiny Realty Solutions",
            "Dream Home Improvements",
            "Dream Home Real Estate Service",
            "Dreamscape Garden Care",
            "Dun Rite Lawn Care",
            "Dun Rite Lawn Maintenance",
            "Dynatronics Accessories",
            "E-zhe Source",
            "Earthworks Garden Kare",
            "Earthworks Yard Maintenance",
            "Eden Lawn Service",
            "Edge Garden Services",
            "Edge Yard Service",
            "Ejecta",
            "Electronic Geek",
            "Electronics Source",
            "Enrich Garden Services",
            "Enviro Architectural Designs",
            "Environ Architectural Design",
            "EnviroSource Design",
            "Envirotecture Design",
            "Envirotecture Design Service",
            "Exact Realty",
            "Exact Solutions",
            "Excella",
            "Express Merchant Service",
            "Fellowship Investments",
            "Fireball",
            "First Choice Garden Maintenance",
            "First Choice Yard Help",
            "First Rate Choice",
            "Fit Tonic",
            "Flexus",
            "Formula Gray",
            "Formula Grey",
            "Four Leaf Clover",
            "Fragrant Flower Lawn Services",
            "Freedom Map",
            "Fresh Start",
            "Friendly Advice",
            "Friendly Interior Design",
            "Full Color",
            "Future Bright",
            "Future Plan",
            "Galaxy Man",
            "Gamma Gas",
            "Gamma Grays",
            "Gamma Realty",
            "Garden Guru",
            "Garden Master",
            "Gas Depot",
            "Gas Legion",
            "Gas Zone",
            "Gold Leaf Garden Management",
            "Gold Touch",
            "Golden Joy",
            "Good Times",
            "Grade A Investment",
            "Grass Roots Yard Services",
            "Grey Fade",
            "Greyvoid",
            "Happy Bear Investment",
            "Happy Family",
            "Helios Air",
            "Helping Hand",
            "Honest Air Group",
            "House of Gas",
            "Hoyden",
            "Idea Infinity",
            "Ideal Garden Maintenance",
            "Ideal Garden Management",
            "Incluesiv",
            "Independent Investors",
            "Independent Wealth Management",
            "Indiewealth",
            "Infinite Wealth",
            "Infinite Wealth Planners",
            "Infinity Investment Plan",
            "Integra Design",
            "Integra Investment Plan",
            "Integra Investment Service",
            "Integra Wealth",
            "Integra Wealth Planners",
            "Intelacard",
            "Intelli Wealth Group",
            "Jackhammer Technologies",
            "Jackpot Consultant",
            "Just For Fun",
            "Knockout Kickboxing",
            "Komerci",
            "Konsili",
            "Landskip Yard Care",
            "Landskip Yard Service",
            "Las Vegas Yard Management",
            "Lawn N' Order Garden Care",
            "Lawnscape Garden Maintenance",
            "Lazysize",
            "Libera",
            "Liberty Wealth Planner",
            "Liberty Wealth Planners",
            "Life Map",
            "Life Map Planners",
            "Life Plan Counselling",
            "Life's Gold",
            "Listen Up",
            "Locost Accessories",
            "Lone Wolf Wealth Planning",
            "Macroserve",
            "Magna Architectural Design",
            "Magna Consulting",
            "Magna Solution",
            "Matrix Architectural Service ",
            "Magik Gray",
            "Magik Grey",
            "Magik Lamp",
            "Magna Architectural Design",
            "Magna Gases",
            "Magna Wealth",
            "MagnaSolution",
            "ManCharm",
            "ManPower",
            "Manu Connection",
            "Maxaprofit",
            "Master Builder Design Services",
            "Matrix Architectural Service",
            "Matrix Design",
            "Matrix Interior Design",
            "Maxi-Tech",
            "Maxiserve ",
            "MegaSolutions",
            "Megatronic",
            "Megatronic Plus",
            "Merrymaking",
            "Micro Design",
            "Mikro Designs",
            "Mikrotechnic",
            "Millenia Life",
            "Mission G",
            "Mission Realty",
            "Mission You",
            "Modern Architecture Design",
            "Modern Realty",
            "Monit",
            "Monlinks",
            "Monk Home Funding Services",
            "Monk Home Improvements",
            "Monk Home Loans",
            "Monk House Maker",
            "Monk House Sales",
            "Monk Real Estate Service",
            "Monmax",
            "Monsource",
            "Multi-Systems Merchant Services",
            "Multi Tech Development",
            "Multicerv",
            "Muscle Factory",
            "Naturohair",
            "Netaid",
            "Netobill",
            "Netcom Business Services",
            "Netcore",
            "Netstars Matrix Design",
            "Network Air",
            "New World",
            "New World Realty",
            "Newhair",
            "Northern Star",
            "Nutri G",
            "Omni Architectural Designs",
            "Omni Realty",
            "Omni Source",
            "Omni Tech",
            "Omni Tech Solutions",
            "One-Up Realtors",
            "One-Up Realty",
            "Opti-Tek",
            "Opticomp",
            "Orion",
            "Parts and Pieces",
            "Pearl Architectural Design",
            "Perisolution",
            "Personal & Corporate Design",
            "Plan Future",
            "Plan Smart",
            "Plan Smart Partner",
            "Planet Profit",
            "Planetbiz",
            "Platinum Interior Design",
            "Pointers",
            "Powerbod",
            "Practi-Plan",
            "Practi-Plan Mapping",
            "Prahject Planner",
            "Prestiga-Biz",
            "Prestigabiz",
            "Pro-Care Garden Maintenance",
            "Pro Garden Management",
            "Pro Property Maintenance",
            "Pro Star",
            "Pro Star Garden Management",
            "Pro Yard Services",
            "Profitpros",
            "Prospa-Pal",
            "Protean",
            "Quality Event Planner",
            "Quality Merchant Services",
            "Quality Realty Service",
            "Quest Technology Service",
            "Quickbiz",
            "Rainbow Life",
            "Realty Depot",
            "Realty Solution",
            "Realty Zone",
            "Red Bears Tavern",
            "Red Fox Tavern",
            "Reliable Garden Management",
            "Reliable Guidance",
            "Reliable Investments",
            "Rich and Happy",
            "Rite Solution",
            "Rivera Property Maintenance",
            "Road Runner Lawn Services",
            "Romp",
            "Royal Gas",
            "Sexy Babe",
            "Seksi Ladi",
            "Seksi Lady",
            "Sexsi Senorita",
            "Sky High Financial Advice",
            "Signa Air",
            "Simple Solutions",
            "Simply Appraisals",
            "Simply Save",
            "Sistemos",
            "Solid Future",
            "Solution Answers",
            "Solution Bridge",
            "Solution Realty",
            "Specific Appraisals",
            "Star Assistance",
            "Star Bright Investment Group",
            "Star Interior Design",
            "Star Merchant Services",
            "StopGrey",
            "Stratabiz",
            "Stratacard",
            "Stratagee",
            "Stratapro",
            "Strategic Profit",
            "Strategy Consulting",
            "Strategy Planner",
            "Strength Gurus",
            "Strongbod",
            "Strong Life",
            "Suadela Investment",
            "Success Is Yours",
            "Sunburst Garden Management",
            "Sunny Real Estate Investments",
            "Superior Appraisals",
            "Superior Interior Design",
            "System Star",
            "System Star Solutions",
            "Target Realty",
            "Target Source",
            "Team Designers and Associates",
            "Team Uno",
            "Techo Solutions",
            "Terra",
            "Terra Nova Garden Services",
            "The Flying Bear",
            "The Fox and Hound ",
            "The Flying Hippo ",
            "The Goose and Duck",
            "The Happy Bear",
            "The High Heelers",
            "The Independent Planners",
            "The Jolly Farmer",
            "The Lawn Guru",
            "The Network Chef",
            "The Pink Pig Tavern",
            "The Polka Dot Bear Tavern",
            "The Serendipity Dip",
            "The Spotted Cougar",
            "The White Rabbit",
            "The White Swan",
            "Titania",
            "Total Network Development",
            "Total Quality",
            "Total Serve",
            "Total Sources",
            "Total Yard Maintenance",
            "Total Yard Management",
            "Universal Design Partners",
            "Universo Realtors",
            "Vari-Tec",
            "Veramons",
            "Vibrant Man",
            "Vitagee",
            "VitaGrey",
            "Vitamax Health Food Center",
            "Wealth Zone Group",
            "Wealthy Ideas",
            "Webcom Business Services",
            "Wise Appraisals",
            "Wise Solutions",
            "World of Fun",
            "WWW Realty",
            "Xray Eye & Vision Clinics",
            "Zephyr Investments",
            "Zig Zag Children Clothes",
            "a21",
            "Aaron's, Inc.",
            "Abbott Laboratories",
            "Abercrombie & Fitch",
            "ABM Industries",
            "ABX Air",
            "AC Lens",
            "ACCO Brands",
            "Accuquote",
            "Ace Hardware",
            "Acme Brick Company",
            "ACN Inc.",
            "Activision Blizzard",
            "Acuity Brands",
            "ADC Telecommunications",
            "Adaptec",
            "Adobe Systems Inc.",
            "Advance Auto Parts",
            "Advanced Micro Devices",
            "Advanced Processing & Imaging",
            "AECOM",
            "AŽropostale",
            "AES Corporation",
            "Applied Industrial Technologies",
            "Applied Materials",
            "Aramark",
            "Arbitron",
            "Arch Coal",
            "Archer Daniels Midland",
            "Arctic Cat",
            "Ariba",
            "Arizona Stock Exchange",
            "Arkeia Software",
            "Armstrong World Industries",
            "Arrow Electronics",
            "Arryx",
            "ArvinMeritor",
            "ASARCO (American Smelting And Refining Company)",
            "Asbury Automotive Group",
            "Ashland Inc.",
            "AskMeNow",
            "Boston Scientific",
            "Boyd Gaming",
            "Bradley Pharmaceuticals",
            "Briggs & Stratton",
            "Brightpoint",
            "Brinks",
            "Brinker International",
            "Bristol-Myers Squibb",
            "Broadcom",
            "Brookdale Senior Living",
            "Brown-Forman Corporation",
            "Brunswick Corporation",
            "Bucyrus International",
            "Burger King Holdings",
            "Burlington Coat Factory",
            "Bushmaster Firearms International",
            "Butler America",
            "Cole Haan",
            "Colgate-Palmolive",
            "Colt Defense",
            "Colt's Manufacturing Company",
            "Columbia Pictures",
            "Columbia Sussex",
            "Comcast",
            "EMC Corporation",
            "Emcor",
            "Emerson Electric Company",
            "Emerson Radio",
            "Energizer Holdings",
            "Energy East",
            "Enterasys Networks",
            "Fairchild Semiconductor",
            "FedEx",
            "Fender Musical Instruments Corporation",
            "Fidelity Investments",
            "FileMaker Inc., formerly Claris Corp.",
            "Firestone Tire and Rubber Company",
            "First Hawaiian Bank",
            "Fiserv",
            "Fisher Electronics",
            "Fisker Automotive",
            "Fluor Corp",
            "Ford Motor Company",
            "Forum Communications",
            "Fox Film Corporation",
            "Frasca International",
            "Fred Meyer, Inc.",
            "FreeWave Technologies",
            "Fresh&Easy Neighbourhood Market",
            "Frontier Airlines",
            "Fruit of the Loom",
            "Federal Home Loan Mortgage Corporation",
            "Federal National Mortgage Association",
            "Gap",
            "Garmin",
            "Gartner",
            "Gateway Computers",
            "Gatorade",
            "GEICO",
            "Hilton Hotels Corporation",
            "H. J. Heinz Company",
            "Home City Ice Co.",
            "Home Depot",
            "Honeywell",
            "Hornbeck Offshore Services",
            "Hot Topic",
            "Houchens Industries",
            "Houlihan's",
            "Human Kinetics",
            "Hunt Petroleum",
            "Hyland Software",
            "Ideal Industries",
            "Imation",
            "Informix",
            "Infor",
            "Intel",
            "Intercontinental Manufacturing Company",
            "International Business Machines (IBM)",
            "International Game Technology (IGT)",
            "International Paper",
            "Interplay Entertainment",
            "Interstate Batteries",
            "Intuit",
            "ION Media Networks",
            "iRobot",
            "Iron Mountain",
            "i-flex Solutions",
            "Jack in the Box",
            "Jarden",
            "JCPenney",
            "JetBlue Airways",
            "Jimmy John's",
            "JL Audio",
            "JN-International Medical Corporation",
            "Jones Soda Co.",
            "Johnson & Johnson",
            "Johnson Controls",
            "Journal Communications",
            "J. P. Morgan Chase and Co.",
            "J. C. Penny",
            "KBR",
            "KFC",
            "Lowe's",
            "Lumencraft",
            "L.L.Bean",
            "L&L Hawaiian Barbecue",
            "Local Matters",
            "Lockheed Martin",
            "Louisiana Pacific",
            "Lucasfilm",
            "Lucas Oil",
            "Magnavox",
            "Marantz",
            "Marathon Oil",
            "Marriott Corporation",
            "Mars Incorporated",
            "Marsh & McLennan",
            "Marshall Pottery",
            "Martel Communication",
            "Martha Stewart Living Omnimedia",
            "Martin Marietta Materials",
            "MasterCard",
            "Mattel",
            "Mauna Loa Macadamia Nut Corp.",
            "Maxtor Corporation",
            "McCormick & Company",
            "McDonald's",
            "MCI Inc.",
            "McIlhenny Company",
            "Medimix International",
            "Meijer",
            "Memorex",
            "Merck and Company",
            "Qpass",
            "Qualcomm",
            "Quanta Services",
            "Quantrix",
            "Quest Software",
            "QuickTrip",
            "Quincy Newspapers",
            "QVC",
            "Qwest",
            "Quiznos",
            "RadioShack",
            "Raytheon",
            "Rayovac",
            "RCA",
            "Red Hat",
            "Red River Broadcasting",
            "Rent-A-Wreck",
            "Renys",
            "Regis Corporation",
            "Respironics, Inc.",
            "Rite Aid Corporation",
            "Riverdeep",
            "Rockford Fosgate",
            "Rockstar Games",
            "Rockwell Automation",
            "Rockwell Collins",
            "Rollins Inc.",
            "Royal Caribbean International",
            "Russell Investment Group",
            "Russell Stovers",
            "Ryder System, Inc.",
            "S3 Graphics",
            "Safeco Corporation",
            "Safeway Inc.",
            "Salary.com",
            "Salem Communications",
            "SanDisk",
            "Sauer-Danfoss",
            "SBC Communications",
            "Schoep's Ice Cream",
            "Science Applications International Corporation (SAIC)",
            "Seagate Technology",
            "Sears",
            "Seattle's Best Coffee",
            "Service Corporation International (SCI)",
            "Sprint Nextel Corporation",
            "Spanx",
            "Spectrum Brands",
            "Spherion",
            "Staples, Inc.",
            "Starbucks",
            "Starz",
            "State Street Corporation",
            "Steinway & Sons",
            "Sterling Ledet & Associates, Inc.",
            "Sterling Commerce",
            "Stewart-Warner",
            "Storage Technology Corporation",
            "STX",
            "Subway",
            "Sunny Delight Beverages",
            "Sun Microsystems, Inc.",
            "Sunoco",
            "Supervalu",
            "Sur La Table",
            "Syntel",
            "Symantec",
            "Taco Tico",
            "Take-Two Interactive",
            "Tanadgusix Corporation",
            "Target Corporation",
            "Tempur-Pedic",
            "Tesla Motors",
            "Tesoro",
            "Testor Corporation",
            "Texas Instruments",
            "Textron Inc.",
            "Ubu Productions",
            "Ultimate Software",
            "Under Armour",
            "Union Oil Company of California (Unocal)",
            "Union Pacific Railroad",
            "Unisys",
            "United Airlines",
            "United Parcel Service (UPS)",
            "United Technologies",
            "Universal Studios",
            "US Airways",
            "U.S. Robotics",
            "UTStarcom",
            "United Services Automobile Association",
            "US Cellular",
            "U.S. Steel",
            "Uwajimaya",
            "Valero Energy Corporation",
            "Vantec",
            "The Vanguard Group",
            "Vaughan & Bushnell Manufacturing",
            "VECO Corporation",
            "VF Corporation",
            "Lee (jeans)",
            "Venus Swimwear",
            "Verbatim Corporation",
            "Vertex Pharmaceuticals",
            "Victoria's Secret",
            "ViewSonic",
            "Vistikon",
            "VIZ Media",
            "Vizio",
            "Vectren",
            "Verizon",
            "Verizon Wireless",
            "WWE",
            "Wynn Resorts",
            "Xerox",
            "Xilinx",
            "XPAC",
            "XPLANE",
            "Yahoo!",
            "YASH Technologies",
            "YRC Worldwide Inc.",
            "Yum! Brands, Inc.",
            "Zapata",
            "Zappos.com",
            "Zaxby's",
            "Zenith Electronics",
            "ZOMM, LLC",
            "Zoo York",
            "Zoom Technologies",
            "Zune"
        };

        readonly Random _random = new Random();

        public Person GeneratePerson()
        {
            return new Person(
            _names[_random.Next(0, _names.Length)] + " " + _surnames[_random.Next(0, _surnames.Length)] + " " + _patronymic[_random.Next(0, _patronymic.Length)], 
            _datesOfBirth[_random.Next(0, _datesOfBirth.Length)],
            _towns[_random.Next(0, _towns.Length)], 
            _passportNumbers[_random.Next(0, _passportNumbers.Length)]
            );
        }
        
        public PersonWithBadHashCode GeneratePersonWithBadHashCode()
        {
            return new PersonWithBadHashCode(
                _names[_random.Next(0, _names.Length)] + " " + _surnames[_random.Next(0, _surnames.Length)] + " " + _patronymic[_random.Next(0, _patronymic.Length)], 
                _datesOfBirth[_random.Next(0, _datesOfBirth.Length)],
                _towns[_random.Next(0, _towns.Length)], 
                _passportNumbers[_random.Next(0, _passportNumbers.Length)]
            );
        }

        public IEnumerable<Person> GeneratePersonArray(int length)
        {
            Person[] array = new Person[length];
            for (int i = 0; i < length; i++)
            {
                array[i] = GeneratePerson();
            }
            return array;
        }

        public Dictionary<Person, string> GeneratePersonWorkPlaceDictionary(int length)
        {
            string directory = Directory.GetCurrentDirectory();
            string writePath = directory + "/GeneratePersonWorkPlaceDictionaryOutput.txt";
            Console.WriteLine("Найти подробный список работников можно здесь: " + directory);
            var random = new Random();
            var dictionary = new Dictionary<Person, string>();
            using (StreamWriter sw = new StreamWriter(writePath, true, System.Text.Encoding.Default))
            {
                for (int i = 0; i < length; i++)
                {
                    var toAdd = GeneratePerson();
                    while (dictionary.ContainsKey(toAdd))
                    {
                        toAdd = GeneratePerson();
                    }
                    dictionary.Add(toAdd, _companies[random.Next(0, _companies.Length)]);
                    sw.WriteLine(toAdd);
                }   
            }
            return dictionary;
        }
        
        public Dictionary<PersonWithBadHashCode, string> GeneratePersonWithBadHashCodeWorkPlaceDictionary(int length)
        {
            var directory = Directory.GetCurrentDirectory();
            var writePath = directory + "/GeneratePersonWorkPlaceDictionaryOutput.txt";
            Console.WriteLine("Найти подробный список работников можно здесь: " + directory);
            var random = new Random();
            var dictionary = new Dictionary<PersonWithBadHashCode, string>();
            using (StreamWriter sw = new StreamWriter(writePath, true, System.Text.Encoding.Default))
            {
                for (int i = 0; i < length; i++)
                {
                    var toAdd = GeneratePersonWithBadHashCode();
                    while (dictionary.ContainsKey(toAdd))
                    {
                        toAdd = GeneratePersonWithBadHashCode();
                    }
                    dictionary.Add(toAdd, _companies[random.Next(0, _companies.Length)]);
                    sw.WriteLine(toAdd);
                }   
            }
            return dictionary;
        }
    }
}